# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vxj0pfc5OJvyfOVJKZRwMxMXL4O9FX3x
"""

def check_winner(board, player):
    # Check rows
    for row in range(3):
        if board[row][0] == board[row][1] == board[row][2] == player:
            return True

    # Check columns
    for col in range(3):
        if board[0][col] == board[1][col] == board[2][col] == player:
            return True

    # Check diagonals
    if board[0][0] == board[1][1] == board[2][2] == player:
        return True

    if board[0][2] == board[1][1] == board[2][0] == player:
        return True

    return False


def board_full(board):
    for row in board:
        if " " in row:
            return False
    return True


def display_board(board):
    for row in board:
        print(" | ".join(row))
        print("-" * 9)


def play_game():
    # 3 x 3 two-dimensional array
    board = [
        [" ", " ", " "],
        [" ", " ", " "],
        [" ", " ", " "]
    ]

    current_player = "X"

    print("TIC-TAC-TOE")
    print("Positions are numbered 1 to 9.")

    while True:
        display_board(board)

        try:
            position = int(
                input(f"Player {current_player}, enter position (1-9): ")
            )

            if position < 1 or position > 9:
                print("Please enter a number between 1 and 9.")
                continue

            # Convert position to row and column
            row = (position - 1) // 3
            col = (position - 1) % 3

            if board[row][col] != " ":
                print("Position already occupied. Try again.")
                continue

            board[row][col] = current_player

            if check_winner(board, current_player):
                display_board(board)
                print(f"Player {current_player} wins!")
                break

            if board_full(board):
                display_board(board)
                print("It's a draw!")
                break

            # Change player
            if current_player == "X":
                current_player = "O"
            else:
                current_player = "X"

        except ValueError:
            print("Please enter a valid number.")


play_game()